live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 2
y = 2

[font]
size = 10.0

[font.bold]
family = "Terminus"
style = "Bold"

[font.bold_italic]
family = "Terminus"
style = "Bold"

[font.italic]
family = "Terminus"
style = "Regular"

[font.normal]
family = "Terminus"
style = "Regular"


